remote/client.go
The TCP connection wouldn't be reused and closed, and increased when had new actions.
Solution:
1. Clear the body of the response, so that the TCP connection can be reused
2. Close the TCP connection if it isn't be used after 90s idle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/110)
=> fix for tcp connection not closed

remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/block_device_utils/errors.go, remote/mounter/block_device_utils/mpath.go
…ests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/164)
=> Added a double validation for multipath device WWN discovered via multipath -ll

remote/mounter/block_device_mounter_utils/block_device_mounter_utils.go, remote/mounter/block_device_utils/mpath.go
1. increase sleep time on mpath lock and rescan lock from 100 to 500ms, so it will have less read IO while waiting for lock (since rescan usually take 1-2 seconds, so no need to have so many retries)
2. Fix wrong debug message in rescanLock (by mistake it was printed as mpathLock). Found by @danapython 
3. Do not run discover during rescan if the rescan was triggered during detach. becuase during detach the discover will always fail and its a waist of time and also it will start run sg_inq on each device which is also waist of time and few error in the log that are not relevant. SO move the discover during rescan only if rescan triggered for attach.  this is help us also to identify when we really have bad WWN show up in the multipath -ll.
4. Change message log from Debug to Error if …
=> Fix/increase locks sleep and run discover only in mount flow (not in unmount flow)

Dockerfile
1. ubiquity base image in GA v1.0 was set to alpine:latest (back then it was alpine version 3.6).
We should not use "latest" tag in dockerfile any more, so I set it to alpine:3.7 which is now the latest alpine version. So setting specific tag version and also upgrade to 3.7.
2. Upgrade alpine 3.7 requires to upgrade also the following packages in the docker image:
ca-certificates  20161130-r2 --> 20171114-r0
openssl          1.0.2k-r0   --> 1.0.2n-r0
Thanks Peeyush gupta @Pensu for indicating about the wrong dependencies with the latest alpine version.
**How to test**
1. Install ubiquity and then jump inside the ubiquity pod and check the new alpine version 
`#> kubectl exec -n ubiquity -it <POD> -- cat /etc/alpine-release`
In addition check the new packages version 
`#> kubectl exec -n …
=> Upgrade image to alpine 3.7. Also upgrade openssl and ca-certificates versions.

database/init.go, database/volume.go, utils/utils.go
get ibm ubiquity db name from ubiquity Pod env setting.
k8s side of thing -> https://github.com/IBM/ubiquity-k8s/pull/167
Signed-off-by: feihuang <feihuang@feihuangs-mbp.cn.ibm.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/186)
=> change ibm-ubiquity-db to configurable

local/scbe/errors.go, local/scbe/scbe_test.go
Update error messages with the new name Spectrum Connect instead of SCBE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/193)
=> Spectrum Connect rebranding texts (phase2)

remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/block_device_utils/mpath.go
Internal ticket UB-1030.
Validate the WWN of the discovered device done by sg_inq. But we have a bug there that the parsing sg_inq output is not working well for XIV because different outline of the sg_inq output.
(was found while testing Ubiquity on zLinux)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/195)
=> Fix sg_inq parsing the WWN during the device discovery.

Dockerfile, scripts/images_verification/ubiquity_image_verification/ubiquity_image_command_test.yaml
openssl-1.0.2o is available since 27-Mar-2018 and is available for all relevant platforms. openssl-1.0.2n is not available on ppc64le.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/205)
=> update openssl to 1.0.2o-r0

fakes/fake_block_device_utils.go, remote/mounter/block_device_mounter_utils/block_device_mounter_utils.go, remote/mounter/block_device_mounter_utils/block_device_utils_mounter_test.go, remote/mounter/block_device_mounter_utils/errors.go, remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/block_device_utils/fs.go, remote/mounter/block_device_utils/resources.go
This PR is for fixing a bug that @danare found in PR #196 (internal issue UB-1230).
Flex mount CLI must prevent mounting a device if the mountpoint is already in used by other device, in order to prevent double mounting on the same directory. 
So this PR fix it and check during the mount flow if the given mountpoint is already in-used (already mounted by other device). If its already mounted to a different device, then error will be raised
"[%s] directory is already a mountpoint but to unexpected devices=%#v (expected mountpoint only on device=[%s])"
**How to test:**
1. Create 2 PVCs (PVC1 & PVC2) and check what is the PV1 WWN (will be used in step 3)
2. Manually create and map PV2 on node1.
3. Manually discover the PV2 the device on the node1 and mkfs and mount it to a directory …
=> Mount flow should fail to mount if the mountpoint is already in-use.

remote/mounter/block_device_mounter_utils/block_device_utils_mounter_test.go, remote/mounter/block_device_mounter_utils/errors.go
@danare found a wrong text in error message in #212.
The error DirPathAlreadyMountedToWrongDevice message was included the variable type. For example : "devices=[]string{"/dev/mapper/mpathv", "/dev/mapper/mpathv2"}".
So this PR fixs the text so it will be "devices=[/dev/mapper/mpathv /dev/mapper/mpathv2]"
In addition, I saw that I didn't align the a fake file with renamed interface isDirAMountPoint. So used this PR to fix that as well, so the UT should pass OK now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/214)
=> Fix error message in mounter_utils (per Dana review UB-1230) and fix fake file

glide.yaml, local/scbe/datamodel.go, local/scbe/datamodel_wrapper.go, local/scbe/errors.go, local/scbe/scbe.go, local/scbe/scbe_rest_client.go, local/scbe/scbe_test.go, resources/resources.go
Refactor volumeNotFoundError in database to be standard error for StorageClient interface.
Move this error from scbe backend to be generic for ubiqutiy StorageClient interface,
So the plugins will be able to identify if the GetVolume interface fail to find the volume because an error or because it was not found in Ubiqutiy DB.
The first to use it in the plugin is the flex Unmount CLI to identify if PV exist in ubiquity before unmount start (for idempotent issue resolving)
This PR related to k8s plugin -> https://github.com/IBM/ubiquity-k8s/pull/193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/216)
=> Fix/Generic error for PV not found in DB (for plugin identification the PV existence)

web_server/storage_api_server.go
added timestamp to start server message: 
`2018-07-01 11:52:15.077 INFO storage_api_server.go:73 web_server::printStartMsg [NA:1] Starting Storage API server on port 9999 .... []
2018-07-01 11:52:15.077 INFO storage_api_server.go:74 web_server::printStartMsg [NA:1] CTL-C to exit/stop Storage API server service []
`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/220)
=> UB-1174: added tiemstamp to starting server log

utils/logs/go_logging_logger.go
Fixed a format error for Warning messages. they will now look as the regular ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/226)
=> UB-1433: fixed earning logs

remote/mounter/block_device_utils/mpath.go
We don't want to see an error every time a volume is being discovered. so i removed the error message and am just returning the error. 
(I don't see a reason to print 2 messages in a row about the same thing this is why I removed the message and not changed it to debug)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/228)
=> UB-605: change message to debug

local/scbe/errors.go, local/scbe/resources.go, local/scbe/simple_rest_client.go, local/scbe/simple_rest_client_test.go
This PR improve the ability to troubleshooting Spectrum Connect http issues, so the errors information will be also visible from the provisioner and flex log (and not only in the ubiqutiy server log).
Currently When ubiqutiy gets http error from Spectrum Connect it raises an error and the plugin(e.g provisioner) will show this error in the log. BUT the problem is that ubiqutiy raised only the http error code and NOT the http data, which may includes the reason of the http error.
So this PR fix it and add new error type that also include the http response data, so the plugins will also show it in there logs.
Internal issue -> UB-115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> expose the http error reason also to the plugins (provisioner\flex)

remote/mounter/block_device_utils/errors.go, remote/mounter/block_device_utils/mpath.go, remote/mounter/mounter_factory.go, remote/mounter/scbe.go, remote/mounter/scbe_test.go
In this PR , the following idempotent issue with Unmount flow is fixed:
if a discovery of a volume fails, no need to fail the Unmount command, just need to skip the UnmountDeviceFlow.
more info:
if volume's mpath NOT discovered (because the device does not exist at all in multipath -ll) then we should skip UnmountDeviceFlow instead of failing (reminder - the UnmountDeviceFlow is the flow that does umount the device and cleanup of the mpath device) .    
Why its idempotent? - because there is a chance that unmount flow will fail  at the end of UnmountDeviceFlow after it unmounts and cleans the mpath device. So to be idempotent the unmount needs to handle unmount request while the mpath device was already cleaned.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> UB-1405: unmount flow should not fail if discovery fails

local/scbe/scbe.go, local/scbe/scbe_test.go
In the ubiquity server if the volume is already detached we will not fail the flow but succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/231)
=> UB-1408: fix idempotent issue#6 - dont raise error on detach in ubiquity server

remote/mounter/scbe.go
added a message to the log to indicate an idempotent case has occurred: 
we skipped the deletion of the mountpoint when it already does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/232)
=> UB-1472: add idempotent message

remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/block_device_utils/errors.go, remote/mounter/block_device_utils/fs.go, remote/mounter/block_device_utils/mpath.go, remote/mounter/block_device_utils/rescan.go
This PR will return the actual error that is returned from sg_inq and not mask it as a volume not found error .
this is important because if we mask the error from sg_inq  we might stumble into an idempotent case and continue the umount even thought we should not and we will be stuck.
(this can happen when there is a faulty device so sg_inq returns an error and we return a volume not found error in this case, and after that because we know to continue with the unmount in case of a volume not found we will continue the umount even though other steps did not happen and this is not really the case of a volume not found because it was already unmounted.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> UB-1475: returning the actual error from the Discover instead of masking it as Volume not found

scripts/helper_to_push_docker_manifest.sh, scripts/helper_to_push_ubiquity_images_and_manifests.sh
Add support for Ubiquity Z images (s390x architecture) in the helper CI scripts. So the CI scripts will also push s390x ubiqutiy images from an internal registry to external registry, and also create the ubiqutiy docker manifest with the new s390x image architecture (before this PR the helper scripts supported only P and X architecture).
Below the description of the CI scripts changes to support Z images:
1. changes in [helper_to_push_docker_manifest.sh]:
- The script gets another argument for Z image (in addition to P and X images). 
- The script pushes also the Z image from internal registry to external registry and creates the manifest with X, P and Z images. 
- In addition the script validates that the new manifest has 3 different architectures.
2. Changes in …
=> Support S390X images in Ubiquity CI helper scripts

fakes/fake_block_device_mounter_utils.go, fakes/fake_block_device_utils.go, remote/mounter/block_device_mounter_utils/block_device_mounter_utils.go, remote/mounter/block_device_mounter_utils/block_device_utils_mounter_test.go, remote/mounter/block_device_mounter_utils/resources.go, remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/block_device_utils/fs.go, remote/mounter/block_device_utils/resources.go, remote/mounter/scbe.go
added a log message to indicate that a device was already unmounted. 
as part of this message we needed to add the volume WWN (to enable the automation to work and check this case) so some changes in the API were made to support this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/233)
=> UB-1474: added logging message to indicate an idempotent issue

Dockerfile
It seams that openssl-1.0.2o-r0 was removed from the Alpine 3.7 repository (http://dl-cdn.alpinelinux.org/alpine/v3.7/main/). It was replaced to this new version 1.0.2o-r1 in 18-Jul-2018 07:29 (40 days ago).  
So we must update the openssl version in the ubiqutiy Dockerfile in order to successfully build the Ubiquity image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/244)
=> UB-1501: Upgrade to openssl-1.0.2o-r1 to align with Alpine 3.7 repo updates.

remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/block_device_utils/mpath.go
if we encounter a bad mpath device we will continue with the scan of the other devices.
(this is based on :https://github.com/IBM/ubiquity/pull/170  + some code review and test fixes changes )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/247)
=> Fix/ub-599 discover by sg_inq should continue scan if bad mpath device

fakes/fake_executor.go, remote/mounter/errors.go, remote/mounter/scbe.go, remote/mounter/scbe_test.go, utils/executor.go
in this PR we want to check before deleting the /ubiquity/wwn folder if there are any files left there. if there are still files(e.g for some reason the mountpoint directory /ubiquity/wwn had some files before the block device mountpoint on it) - an ERROR will be raised until the folder will be cleaned of files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/248)
=> remove mountpoint safely

local/clients.go, local/clients_test.go, local/spectrumscale/connectors/connectors.go, local/spectrumscale/connectors/rest.go, local/spectrumscale/connectors/rest_v2.go, local/spectrumscale/connectors/rest_v2_test.go, local/spectrumscale/spectrumscale.go, resources/resources.go, utils/utils.go
UB-1487 : Using ManagementIP and Port instead of accepting URL for endpoint
UB-1488 : Using SPECTRUMSCALE_ prefix instead of SSC_
UB-1495 : Improve the check in backend initilization. Added check for scbe backend. Check for Spectrum Scale will be added later.
Removed MMCLI and MMSSH backend initialization as they are no longer valid
Removed sshconfig from resource.go because it is no longer required
Minor updates in test to use ManagementIP and Port instead of Endpoint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/243)
=> Spectrumscale-epic1 fix for UB-1487,UB-1488,UB-1495

Dockerfile
1. upgrade ubiqutiy server from Alpine 3.7 to 3.8
2. Due to Alpine upgrade, we should upgrade openssl from 1.0.2o-r1   to  openssl-1.0.2p-r0. (To aligned based on list mentioned [HERE](http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/) )
3. Due to Alpine upgrade, we should upgrafr ca-certificates from 20171114-r0 to 20171114-r3.
Also related to https://github.com/IBM/ubiquity-k8s/pull/217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/251)
=> Feature/upgrade Alpine3.8, openssl and ca-certificates

local/spectrumscale/connectors/rest_v2.go, local/spectrumscale/connectors/rest_v2_test.go, local/spectrumscale/errors.go, local/spectrumscale/spectrumscale.go, local/spectrumscale/spectrumscale_test.go
- Using reset JobID in the rest call instead of using in filter.
- Updated testcases.
- Handled existing fileset functionality differently using isPreexisting flag in storageClass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/270)
=> rest usage optimazation

local/spectrumscale/connectors/resources.go
Fixing the paging variable type to Pages instead of string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/273)
=> spectrumscale fixing Paging variable type

scripts/ubiquity-postgresql/Dockerfile, scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh
Fix description:
- The  mount point is changed to a different folder - ssl/provided - change is in K8s yaml files
- If the private key and certificate are provided through a secret, they will be copied to the ssl/private folder from the ssl/provided folder and then the owner and file mod is changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/278)
=> UB-1731 - ubiquitydb start script modified to copy cert to a different location

remote/client.go, remote/client_init.go
helm install takes ~3.5 mins, while provisioner activation takes ~2 mins. The root cause is that the default timeout interval for a http request is very long. This PR:
1. set a short timeout for every request (10 seconds)
2. set a shorter timeout for activation (2 seconds) and retry 30 times if it fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/291)
=> UB-1622 provisioner long time for start in the installation phase

local/scbe/resources.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/292)
=> UB-1857: chagne cluster id to be an integer instead of string

remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/block_device_utils/fs.go
Flex mount the /ubiquity/<WWN> without any special chmod setting, so it takes the system umask.
To make it explicitly flex will chmod 775 /ubiquity/<WWN> after the mount operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/295)
=> UB-1814 : Set PV mountpoint chmod to 775

remote/mounter/block_device_mounter_utils/block_device_utils_mounter_test.go, remote/mounter/block_device_utils/block_device_utils_test.go, remote/mounter/initiator/connectors/fibre_channel_test.go, remote/mounter/initiator/linuxfc.go, remote/mounter/initiator/linuxfc_test.go, remote/mounter/scbe.go, remote/mounter/scbe_test.go, resources/resources.go
change LunNumber from float64 to int.
LunNumber should be int, but after json.Marshal and json.UNmarshal it will become float64.
see https://stackoverflow.com/questions/39152481/unmarshaling-a-json-integer-to-an-empty-interface-results-in-wrong-type-assertio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/296)
=> change LunNumber from float64 to int

remote/mounter/block_device_utils/mpath.go, utils/mpath.go, utils/mpath_test.go
The multipath output might print some warning messages if some devices are faulty, it has impact on the function isDeviceFaulty. I have no time to improve this fucntion, I will exclude these messages in 2.1 release.
Here is an example output:
```
Apr 04 16:13:40 | sde: couldn't get target port group
Apr 04 16:13:40 | sdd: couldn't get target port group
mpathj (3600507680c8701159800000000001af4) dm-17 IBM     ,2145            
size=1.0G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| `- 39:0:0:1 sde 8:64 failed faulty running
`-+- policy='service-time 0' prio=0 status=enabled
`- 40:0:0:1 sdd 8:48 failed faulty running
mpathi (3600507680c8701159800000000001af3) dm-14 IBM     ,2145            
size=20G features='1 queue_if_no_path' …
```
=> UB-1977 exclude the warning messages in multipath output
