IBM/ubiquity

README.md
Signed-off-by: Shay Berman <shaybery@gmail.com>
=> Fixes k8s link

README.md, contribution-guide.md, local/spectrumscale/connectors/connectors.go, scripts/run_units.sh
=> Contributor guide

README.md, local/spectrumscale/connectors/mmcli.go, local/spectrumscale/spectrumscale.go, local/spectrumscale/spectrumscale_nfs.go, remote/mounter/nfs.go, remote/mounter/spectrumscale.go, resources/resources.go, ubiquity-server.conf, utils/executor.go
Improve Error handling in Executor and pass quota errors back to the user
Change config name of defaultFilesystem to defaultFilesystemName
=> Better Error handling and config changes

local/scbe/errors.go, local/scbe/scbe.go, local/scbe/scbe_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/58)
=> #57 : Do not allow to delete a volume that is in use

contribution-guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/80)
=> Update contribution-guide.md 

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/86)
=> Update README.md for POC

database/connection.go, database/migrate.go, local/scbe/datamodel.go, local/scbe/datamodel_wrapper.go, local/scbe/datamodel_wrapper_test.go, local/scbe/scbe_rest_client_integration_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/93)
=>  #90: configurable database

resources/resources.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/100)
=>  #99: add credentials to all requests

main.go, web_server/storage_api_server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/105)
=>  #104: use TLS certificates in server

remote/client.go, remote/client_init.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/106)
=> #104: use TLS certificates in plugin

scripts/ubiquity-postgresql/Dockerfile, scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-ssl.sh, scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/108)
=>  #107 - create image for secured postgresql

local/spectrumscale/connectors/mmcli_test.go, local/spectrumscale/connectors/ssh.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/85)
=> Fixed export NFS in ssh connector

ibm-block-storage-via-scbe.md, local/scbe/scbe.go, local/scbe/scbe_rest_client.go, local/scbe/scbe_rest_client_integration_test.go, local/scbe/scbe_rest_client_test.go, local/scbe/simple_rest_client.go, local/scbe/simple_rest_client_test.go, resources/resources.go, ubiquity-server.conf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/111)
=>  #104: use TLS certificates in scbe backend

database/init.go, database/init_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/116)
=>  #90: add connection params to psql init

database/init.go, local/spectrumscale/connectors/mmcli_test.go, local/spectrumscale/connectors/ssh.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/117)
=> pull from DEV to containerized branch (to get DB TIMEOUT connection feature lior added)

remote/client_init.go, resources/resources.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/120)
=>  #104: use TLS certificates in flex

remote/mounter/block_device_utils/fs.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/122)
=> #121: fixed umount error by removing duplicate umount call

Dockerfile, docker-entrypoint.sh, scripts/ubiquity-postgresql/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/124)
=>  #123 - generate CA signed certificate if not provided

Dockerfile, database/init.go, database/init_test.go, docker-entrypoint.sh, local/scbe/errors.go, local/scbe/simple_rest_client.go, local/scbe/simple_rest_client_test.go, remote/client_init.go, remote/client_init_test.go, remote/remote_suite_test.go, resources/resources.go, scripts/run_units.sh, scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-user-db.sh, scripts/ubiquity-postgresql/ubiquity-docker-entrypoint.sh, web_server/storage_api_server.go
Detail about the PR -> #133
and it also linked to ubiquity-k8s PR -> https://github.com/IBM/ubiquity-k8s/pull/105
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/134)
=> #133 : UseSSL is true by default + SSL_MODE setting with require default

glide.yaml, local/scbe/scbe.go, local/scbe/scbe_rest_client_gen.go, local/scbe/scbe_test.go, local/scbe/simple_rest_client.go
#99: add scbe rest client headers sync management
#99: add tests for scbe rest client multiple instances
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/136)
=>  #99: add scbe rest client map for authentication

glide.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/140)
=> UB-392: align glide versions

local/spectrumscale/connectors/connectors_suite_test.go, local/spectrumscale/connectors/rest.go, local/spectrumscale/connectors/rest_v2.go, main.go, remote/client.go, remote/client_init.go, utils/http_utils.go, utils/logger_utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/139)
=> init only stdout logger

fakes/fake_ScbeDataModel.go, fakes/fake_scbe_data_model_wrapper.go, local/scbe/datamodel.go, local/scbe/datamodel_wrapper.go, local/scbe/datamodel_wrapper_test.go, local/scbe/scbe.go, local/scbe/scbe_rest_client_integration_test.go, local/scbe/scbe_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/141)
=> get host attach from scbe instead of database

main.go, utils/heartbeat.go, utils/utils.go, web_server/storage_api_handler.go, web_server/storage_api_server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/142)
=> Update ubiqutiy to use the new Logger (drop the old one)

remote/mounter/scbe.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/145)
=> use ISCSI config in rescan for cleanup

local/scbe/errors.go, local/scbe/scbe_test.go, remote/mounter/block_device_utils/errors.go, resources/resources.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/148)
=> modify error messages

database/connection.go, database/init.go, database/init_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/146)
=> hide db passowrd in the log print

main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/147)
=> hide password in the log print

ibm-block-storage-via-scbe.md, local/scbe/scbe_rest_client.go, local/scbe/scbe_rest_client_integration_test.go, local/scbe/scbe_rest_client_test.go, main.go, remote/mounter/scbe.go, utils/heartbeat.go, utils/utils.go, web_server/storage_api_handler.go, web_server/storage_api_server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/144)
=> UB-379: update SCB interface name to Containers

local/scbe/errors.go, local/scbe/scbe_rest_client.go, local/scbe/scbe_rest_client_test.go, local/scbe/scbe_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/150)
=> Get map ut liort

glide.yaml, remote/mounter/block_device_mounter_utils/block_device_mounter_utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/151)
=> replace rescan and mpath mutex with filelock

glide.yaml, local/scbe/scbe.go, local/scbe/simple_rest_client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/153)
=> move from vendor syncmap to nativ golang syncmap

Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/154)
=> update golang 1.9.0 -> 1.9.1

local/scbe/scbe_rest_client.go, local/scbe/scbe_rest_client_integration_test.go, local/scbe/simple_rest_client.go, local/scbe/simple_rest_client_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/155)
=> fix rest client action without token

remote/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/156)
=> fix error msg to be native type

remote/client.go, utils/http_utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/157)
=> fix double close on error messages and leaks in body response not closed

local/scbe/simple_rest_client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/160)
=> fix leak in body response

scripts/images_verification/ubiquity_db_image_verification/ubiquity_db_image_command_test.yaml, scripts/images_verification/ubiquity_db_image_verification/ubiquity_db_image_file_exist_test.yaml, scripts/images_verification/ubiquity_db_image_verification/ubiquity_db_image_metadata_test.yaml, scripts/images_verification/ubiquity_image_verification/ubiquity_image_command_test.yaml, scripts/images_verification/ubiquity_image_verification/ubiquity_image_file_exist_test.yaml, scripts/images_verification/ubiquity_image_verification/ubiquity_image_metadata_test.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/188)
=> Add image verification for ubiquity and ubiquity-db

scripts/helper_to_push_internal_images_2hub.sh
This script help to push docker images from our internal Docker registry to the public one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/191)
=> Add helper script to push internal images to dockerhub

README.md, contribution-guide.md
Spectrum Control Base Edition was renamed to Spectrum Connect.
So this PR is for align the README file according and also few fixes in the Update contribution-guide.md file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/192)
=> Spectrum connect rebranding

scripts/notices_file_for_ibm_storage_enabler_for_containers
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/197)
=> update notices file for version 1.1.0

README.md, scripts/notices_file_for_ibm_storage_enabler_for_containers
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/200)
=> Dev to master, README update

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/202)
=> Dev - README update

Dockerfile, scripts/helper_to_push_internal_images_2hub.sh, scripts/helper_to_push_manifest.sh, scripts/helper_to_push_ubiquity_images_and_manifests.sh, scripts/images_verification/ubiquity_image_verification/ubiquity_image_command_test.yaml, scripts/notices_file_for_ibm_storage_enabler_for_containers
update openssl to 1.0.2o-r0  (for power and also for x86)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/208)
=> v1.1.1 for power support 

Dockerfile, scripts/helper_to_push_internal_images_2hub.sh, scripts/helper_to_push_manifest.sh, scripts/helper_to_push_ubiquity_images_and_manifests.sh, scripts/images_verification/ubiquity_image_verification/ubiquity_image_command_test.yaml, scripts/notices_file_for_ibm_storage_enabler_for_containers
just merged v1.1.1 branch to master and now i want to merge it also to dev.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/210)
=> Merge v1.1.1 to dev branch (Add support for IBM Power Systems)

Dockerfile, glide.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/224)
=> Add dependencies to glide.yaml to enable Docker's caching

glide.yaml
Resolve Build conflict in Ubiquity-k8s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/235)
=> set dependency version of k8s.io/apimachinery

scripts/notices_file_for_ibm_storage_enabler_for_containers
update notices file for the new version 1.2.0 (Internal ticket UB-1479)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/239)
=> Update notices file for version 1.2

fakes/fake_spectrum.go, local/scbe/datamodel_wrapper.go, local/scbe/datamodel_wrapper_test.go, local/scbe/errors.go, local/scbe/scbe.go, local/scbe/scbe_rest_client.go, local/scbe/scbe_test.go, local/scbe/simple_rest_client.go, local/spectrumscale/connectors/connectors.go, local/spectrumscale/connectors/resources.go, local/spectrumscale/connectors/rest_v2.go, local/spectrumscale/connectors/rest_v2_test.go, local/spectrumscale/errors.go, local/spectrumscale/spectrumscale.go, local/spectrumscale/spectrumscale_test.go, remote/mounter/spectrumscale.go, resources/resources.go, web_server/storage_api_handler.go
- Parameter Validation
- Added check before initialising the Spectrumscale backend
- Added check before the creation of fileset
- changed chown to spectrum scale native rest command
- Get Mount point from the spectrum scale configuration
- Check for quota before the creation of fileset
- UT change and Addition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/263)
=> Spectrumscale validation

remote/mounter/scbe.go
added wwn to logging message for automation purposes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/277)
=> Ub-1734: added wwn to log message

Dockerfile, scripts/notices_file_for_ibm_storage_enabler_for_containers
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/279)
=> Upgrade the alpine3.8 openssl to 1.0.2q

database/migrate.go, local/scbe/scbe_rest_client.go, scripts/ubiquity-postgresql/Dockerfile, scripts/ubiquity-postgresql/docker-entrypoint-initdb.d/init-db-tuning.sh, utils/locker.go
to align the changes from the release branch to dev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/287)
=> merge release v2.0.0 branch to DEV

scripts/build_images.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/289)
=> UB-211: add image build CI script to the repo

scripts/notices_file_for_ibm_storage_enabler_for_containers
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/297)
=> Update notices file for v2.1.0

main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/300)
=> UB-1956: hide scale password in REST requests

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ubiquity/301)
=> Remove ubiquity slack notifications
